# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jul  3 16:17:05 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(914, 706)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 894, 686))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(880, 560))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.logbrowser = QtGui.QTextEdit(self.scrollAreaWidgetContents_3)
        self.logbrowser.setGeometry(QtCore.QRect(600, 40, 291, 271))
        self.logbrowser.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.logbrowser.setReadOnly(True)
        self.logbrowser.setObjectName(_fromUtf8("logbrowser"))
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_13.setGeometry(QtCore.QRect(600, 10, 31, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.mocapframe = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.mocapframe.setGeometry(QtCore.QRect(10, 180, 281, 181))
        self.mocapframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mocapframe.setFrameShadow(QtGui.QFrame.Raised)
        self.mocapframe.setObjectName(_fromUtf8("mocapframe"))
        self.mocapspinbox = QtGui.QSpinBox(self.mocapframe)
        self.mocapspinbox.setGeometry(QtCore.QRect(150, 120, 71, 27))
        self.mocapspinbox.setMaximum(200)
        self.mocapspinbox.setSingleStep(0)
        self.mocapspinbox.setProperty("value", 60)
        self.mocapspinbox.setObjectName(_fromUtf8("mocapspinbox"))
        self.xposlabel = QtGui.QLabel(self.mocapframe)
        self.xposlabel.setGeometry(QtCore.QRect(210, 10, 61, 17))
        self.xposlabel.setObjectName(_fromUtf8("xposlabel"))
        self.yposlabel = QtGui.QLabel(self.mocapframe)
        self.yposlabel.setGeometry(QtCore.QRect(210, 30, 61, 17))
        self.yposlabel.setObjectName(_fromUtf8("yposlabel"))
        self.enablemocapbutton = QtGui.QPushButton(self.mocapframe)
        self.enablemocapbutton.setGeometry(QtCore.QRect(10, 10, 111, 81))
        self.enablemocapbutton.setCheckable(True)
        self.enablemocapbutton.setObjectName(_fromUtf8("enablemocapbutton"))
        self.deslabel1 = QtGui.QLabel(self.mocapframe)
        self.deslabel1.setGeometry(QtCore.QRect(130, 10, 71, 17))
        self.deslabel1.setObjectName(_fromUtf8("deslabel1"))
        self.rotposlabel = QtGui.QLabel(self.mocapframe)
        self.rotposlabel.setGeometry(QtCore.QRect(210, 50, 61, 17))
        self.rotposlabel.setObjectName(_fromUtf8("rotposlabel"))
        self.label = QtGui.QLabel(self.mocapframe)
        self.label.setGeometry(QtCore.QRect(10, 120, 141, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.deslabel3 = QtGui.QLabel(self.mocapframe)
        self.deslabel3.setGeometry(QtCore.QRect(130, 50, 71, 17))
        self.deslabel3.setObjectName(_fromUtf8("deslabel3"))
        self.deslabel2 = QtGui.QLabel(self.mocapframe)
        self.deslabel2.setGeometry(QtCore.QRect(130, 30, 71, 17))
        self.deslabel2.setObjectName(_fromUtf8("deslabel2"))
        self.label_9 = QtGui.QLabel(self.mocapframe)
        self.label_9.setGeometry(QtCore.QRect(230, 120, 21, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.bodynumberspinbox = QtGui.QSpinBox(self.mocapframe)
        self.bodynumberspinbox.setGeometry(QtCore.QRect(150, 150, 71, 27))
        self.bodynumberspinbox.setMinimum(1)
        self.bodynumberspinbox.setObjectName(_fromUtf8("bodynumberspinbox"))
        self.label_11 = QtGui.QLabel(self.mocapframe)
        self.label_11.setGeometry(QtCore.QRect(50, 150, 91, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_15 = QtGui.QLabel(self.mocapframe)
        self.label_15.setGeometry(QtCore.QRect(130, 70, 141, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.mocapflabel = QtGui.QLabel(self.mocapframe)
        self.mocapflabel.setGeometry(QtCore.QRect(130, 90, 141, 21))
        self.mocapflabel.setObjectName(_fromUtf8("mocapflabel"))
        self.autocontrolframe = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.autocontrolframe.setGeometry(QtCore.QRect(310, 340, 281, 281))
        self.autocontrolframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.autocontrolframe.setFrameShadow(QtGui.QFrame.Raised)
        self.autocontrolframe.setObjectName(_fromUtf8("autocontrolframe"))
        self.autocontrolbutton = QtGui.QPushButton(self.autocontrolframe)
        self.autocontrolbutton.setEnabled(False)
        self.autocontrolbutton.setGeometry(QtCore.QRect(10, 10, 111, 81))
        self.autocontrolbutton.setCheckable(True)
        self.autocontrolbutton.setObjectName(_fromUtf8("autocontrolbutton"))
        self.xstartspinbox = QtGui.QDoubleSpinBox(self.autocontrolframe)
        self.xstartspinbox.setGeometry(QtCore.QRect(30, 120, 71, 27))
        self.xstartspinbox.setMinimum(-4.0)
        self.xstartspinbox.setMaximum(4.0)
        self.xstartspinbox.setSingleStep(0.1)
        self.xstartspinbox.setObjectName(_fromUtf8("xstartspinbox"))
        self.ystartspinbox = QtGui.QDoubleSpinBox(self.autocontrolframe)
        self.ystartspinbox.setGeometry(QtCore.QRect(30, 160, 71, 27))
        self.ystartspinbox.setMinimum(-4.0)
        self.ystartspinbox.setMaximum(4.0)
        self.ystartspinbox.setSingleStep(0.1)
        self.ystartspinbox.setObjectName(_fromUtf8("ystartspinbox"))
        self.xgoalspinbox = QtGui.QDoubleSpinBox(self.autocontrolframe)
        self.xgoalspinbox.setGeometry(QtCore.QRect(130, 120, 71, 27))
        self.xgoalspinbox.setMinimum(-4.0)
        self.xgoalspinbox.setMaximum(4.0)
        self.xgoalspinbox.setSingleStep(0.1)
        self.xgoalspinbox.setObjectName(_fromUtf8("xgoalspinbox"))
        self.ygoalspinbox = QtGui.QDoubleSpinBox(self.autocontrolframe)
        self.ygoalspinbox.setGeometry(QtCore.QRect(130, 160, 71, 27))
        self.ygoalspinbox.setMinimum(-4.0)
        self.ygoalspinbox.setMaximum(4.0)
        self.ygoalspinbox.setSingleStep(0.1)
        self.ygoalspinbox.setObjectName(_fromUtf8("ygoalspinbox"))
        self.label_16 = QtGui.QLabel(self.autocontrolframe)
        self.label_16.setGeometry(QtCore.QRect(30, 100, 41, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.autocontrolframe)
        self.label_17.setGeometry(QtCore.QRect(130, 100, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.autocontrolframe)
        self.label_18.setGeometry(QtCore.QRect(10, 120, 16, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.autocontrolframe)
        self.label_19.setGeometry(QtCore.QRect(10, 160, 16, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.usecurposbutton = QtGui.QPushButton(self.autocontrolframe)
        self.usecurposbutton.setEnabled(False)
        self.usecurposbutton.setGeometry(QtCore.QRect(10, 200, 91, 41))
        self.usecurposbutton.setObjectName(_fromUtf8("usecurposbutton"))
        self.startnodecombobox = QtGui.QComboBox(self.autocontrolframe)
        self.startnodecombobox.setGeometry(QtCore.QRect(50, 250, 51, 27))
        self.startnodecombobox.setObjectName(_fromUtf8("startnodecombobox"))
        self.label_21 = QtGui.QLabel(self.autocontrolframe)
        self.label_21.setGeometry(QtCore.QRect(10, 250, 41, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.goalnodecombobox = QtGui.QComboBox(self.autocontrolframe)
        self.goalnodecombobox.setGeometry(QtCore.QRect(130, 250, 51, 27))
        self.goalnodecombobox.setObjectName(_fromUtf8("goalnodecombobox"))
        self.sendgoalbutton = QtGui.QPushButton(self.autocontrolframe)
        self.sendgoalbutton.setEnabled(False)
        self.sendgoalbutton.setGeometry(QtCore.QRect(130, 50, 98, 41))
        self.sendgoalbutton.setObjectName(_fromUtf8("sendgoalbutton"))
        self.controlframe = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.controlframe.setGeometry(QtCore.QRect(10, 10, 281, 161))
        self.controlframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.controlframe.setFrameShadow(QtGui.QFrame.Raised)
        self.controlframe.setObjectName(_fromUtf8("controlframe"))
        self.label_2 = QtGui.QLabel(self.controlframe)
        self.label_2.setGeometry(QtCore.QRect(130, 0, 141, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.enablecontrolbutton = QtGui.QPushButton(self.controlframe)
        self.enablecontrolbutton.setGeometry(QtCore.QRect(10, 10, 111, 81))
        self.enablecontrolbutton.setCheckable(True)
        self.enablecontrolbutton.setObjectName(_fromUtf8("enablecontrolbutton"))
        self.label_10 = QtGui.QLabel(self.controlframe)
        self.label_10.setGeometry(QtCore.QRect(200, 20, 21, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.controlspinbox = QtGui.QDoubleSpinBox(self.controlframe)
        self.controlspinbox.setGeometry(QtCore.QRect(130, 20, 62, 27))
        self.controlspinbox.setMaximum(10.0)
        self.controlspinbox.setSingleStep(0.1)
        self.controlspinbox.setProperty("value", 1.0)
        self.controlspinbox.setObjectName(_fromUtf8("controlspinbox"))
        self.label_12 = QtGui.QLabel(self.controlframe)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 31, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.portlineedit = QtGui.QLineEdit(self.controlframe)
        self.portlineedit.setGeometry(QtCore.QRect(50, 100, 221, 27))
        self.portlineedit.setObjectName(_fromUtf8("portlineedit"))
        self.label_14 = QtGui.QLabel(self.controlframe)
        self.label_14.setGeometry(QtCore.QRect(130, 50, 141, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.controlflabel = QtGui.QLabel(self.controlframe)
        self.controlflabel.setGeometry(QtCore.QRect(130, 70, 141, 21))
        self.controlflabel.setObjectName(_fromUtf8("controlflabel"))
        self.simulationCheckBox = QtGui.QCheckBox(self.controlframe)
        self.simulationCheckBox.setGeometry(QtCore.QRect(10, 130, 131, 20))
        self.simulationCheckBox.setObjectName(_fromUtf8("simulationCheckBox"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_3.setGeometry(QtCore.QRect(10, 360, 66, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setGeometry(QtCore.QRect(305, 10, 111, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.manualcontrolframe = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.manualcontrolframe.setGeometry(QtCore.QRect(305, 40, 281, 271))
        self.manualcontrolframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.manualcontrolframe.setFrameShadow(QtGui.QFrame.Raised)
        self.manualcontrolframe.setObjectName(_fromUtf8("manualcontrolframe"))
        self.backwardbutton = QtGui.QPushButton(self.manualcontrolframe)
        self.backwardbutton.setEnabled(False)
        self.backwardbutton.setGeometry(QtCore.QRect(100, 130, 71, 61))
        self.backwardbutton.setObjectName(_fromUtf8("backwardbutton"))
        self.rightbutton = QtGui.QPushButton(self.manualcontrolframe)
        self.rightbutton.setEnabled(False)
        self.rightbutton.setGeometry(QtCore.QRect(170, 70, 71, 61))
        self.rightbutton.setObjectName(_fromUtf8("rightbutton"))
        self.leftbutton = QtGui.QPushButton(self.manualcontrolframe)
        self.leftbutton.setEnabled(False)
        self.leftbutton.setGeometry(QtCore.QRect(30, 70, 71, 61))
        self.leftbutton.setObjectName(_fromUtf8("leftbutton"))
        self.forwardbutton = QtGui.QPushButton(self.manualcontrolframe)
        self.forwardbutton.setEnabled(False)
        self.forwardbutton.setGeometry(QtCore.QRect(100, 10, 71, 61))
        self.forwardbutton.setObjectName(_fromUtf8("forwardbutton"))
        self.controlpowsspinbox = QtGui.QSpinBox(self.manualcontrolframe)
        self.controlpowsspinbox.setGeometry(QtCore.QRect(180, 210, 60, 27))
        self.controlpowsspinbox.setMaximum(500)
        self.controlpowsspinbox.setProperty("value", 200)
        self.controlpowsspinbox.setObjectName(_fromUtf8("controlpowsspinbox"))
        self.label_6 = QtGui.QLabel(self.manualcontrolframe)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 161, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.manualcontrolframe)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 161, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.controlpowrspinbox = QtGui.QSpinBox(self.manualcontrolframe)
        self.controlpowrspinbox.setGeometry(QtCore.QRect(180, 240, 60, 27))
        self.controlpowrspinbox.setMaximum(500)
        self.controlpowrspinbox.setProperty("value", 200)
        self.controlpowrspinbox.setObjectName(_fromUtf8("controlpowrspinbox"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_7.setGeometry(QtCore.QRect(305, 320, 141, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.loggingframe = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.loggingframe.setGeometry(QtCore.QRect(10, 380, 281, 191))
        self.loggingframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.loggingframe.setFrameShadow(QtGui.QFrame.Raised)
        self.loggingframe.setObjectName(_fromUtf8("loggingframe"))
        self.logfilelineedit = QtGui.QLineEdit(self.loggingframe)
        self.logfilelineedit.setGeometry(QtCore.QRect(10, 60, 261, 27))
        self.logfilelineedit.setObjectName(_fromUtf8("logfilelineedit"))
        self.loggingbutton = QtGui.QPushButton(self.loggingframe)
        self.loggingbutton.setGeometry(QtCore.QRect(10, 10, 98, 27))
        self.loggingbutton.setObjectName(_fromUtf8("loggingbutton"))
        self.label_4 = QtGui.QLabel(self.loggingframe)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 66, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.logbutton = QtGui.QPushButton(self.loggingframe)
        self.logbutton.setEnabled(False)
        self.logbutton.setGeometry(QtCore.QRect(10, 90, 111, 81))
        self.logbutton.setCheckable(True)
        self.logbutton.setObjectName(_fromUtf8("logbutton"))
        self.serialPrintbrowser = QtGui.QTextEdit(self.scrollAreaWidgetContents_3)
        self.serialPrintbrowser.setGeometry(QtCore.QRect(600, 340, 291, 331))
        self.serialPrintbrowser.setObjectName(_fromUtf8("serialPrintbrowser"))
        self.serialPrintbrowser.setReadOnly(True)
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_20.setGeometry(QtCore.QRect(600, 320, 111, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_13.setText(_translate("MainWindow", "Log", None))
        self.xposlabel.setText(_translate("MainWindow", "0", None))
        self.yposlabel.setText(_translate("MainWindow", "0", None))
        self.enablemocapbutton.setText(_translate("MainWindow", "MoCap On", None))
        self.deslabel1.setText(_translate("MainWindow", "X-Position", None))
        self.rotposlabel.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "Sampling Frequency", None))
        self.deslabel3.setText(_translate("MainWindow", "Rotation", None))
        self.deslabel2.setText(_translate("MainWindow", "Y-Position", None))
        self.label_9.setText(_translate("MainWindow", "Hz", None))
        self.label_11.setText(_translate("MainWindow", "Body Number", None))
        self.label_15.setText(_translate("MainWindow", "Actual Frequency", None))
        self.mocapflabel.setText(_translate("MainWindow", "0 Hz", None))
        self.autocontrolbutton.setText(_translate("MainWindow", "Automatic\n"
"Control On", None))
        self.label_16.setText(_translate("MainWindow", "Start", None))
        self.label_17.setText(_translate("MainWindow", "Goal", None))
        self.label_18.setText(_translate("MainWindow", "x", None))
        self.label_19.setText(_translate("MainWindow", "y", None))
        self.usecurposbutton.setText(_translate("MainWindow", "Use Current\n"
"Position", None))
        self.label_21.setText(_translate("MainWindow", "node", None))
        self.sendgoalbutton.setText(_translate("MainWindow", "Send New\n"
"Goal", None))
        self.label_2.setText(_translate("MainWindow", "Sampling Frequency", None))
        self.enablecontrolbutton.setText(_translate("MainWindow", "Control On", None))
        self.label_10.setText(_translate("MainWindow", "Hz", None))
        self.label_12.setText(_translate("MainWindow", "Port", None))
        self.portlineedit.setText(_translate("MainWindow", "/dev/ttyUSB0", None))
        self.label_14.setText(_translate("MainWindow", "Actual Frequency", None))
        self.controlflabel.setText(_translate("MainWindow", "0 Hz", None))
        self.simulationCheckBox.setText(_translate("MainWindow", "Activate Simulation", None))
        self.label_3.setText(_translate("MainWindow", "Logging", None))
        self.label_5.setText(_translate("MainWindow", "Manual Control", None))
        self.backwardbutton.setText(_translate("MainWindow", "Backward", None))
        self.rightbutton.setText(_translate("MainWindow", "Rotate\n"
"Right", None))
        self.leftbutton.setText(_translate("MainWindow", "Rotate\n"
"Left", None))
        self.forwardbutton.setText(_translate("MainWindow", "Forward", None))
        self.label_6.setText(_translate("MainWindow", "Control Power Straight", None))
        self.label_8.setText(_translate("MainWindow", "Control Power Rotation", None))
        self.label_7.setText(_translate("MainWindow", "Automatic Control", None))
        self.logfilelineedit.setText(_translate("MainWindow", "/", None))
        self.loggingbutton.setText(_translate("MainWindow", "Select File", None))
        self.label_4.setText(_translate("MainWindow", "File", None))
        self.logbutton.setText(_translate("MainWindow", "Logging On", None))
        self.label_20.setText(_translate("MainWindow", "Serial.print outputs", None))

